trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: "Build"
    jobs:
      - template: build.yml

  - stage: SAST
    displayName: "Static Analysis"
    dependsOn: Build
    jobs:
      - template: sast.yml

  - stage: Release
    displayName: "Publish Artifact"
    dependsOn: SAST
    jobs:
      - template: release.yml

  - stage: Deploy
    displayName: "Deploy to Remote Server"
    dependsOn: Release
    jobs:
      - template: deploy.yml
